
name: DEV Package Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  dev:
    name: DEV Dry Run
    uses: ./.github/workflows/package-operations.yml
    with:
      environment: dev
      package_name: maximo-demo-package
      dry_run: true
